//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]


namespace Recipe9
{
    #region Contexts
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            OnContextCreated();
        }
        #endregion
        
        #region Partial Methods
        partial void OnContextCreated();
        #endregion
        
        #region ObjectSet Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MovieRental> MovieRentals
        {
            get
            {
                if ((_MovieRentals == null))
                {
                    _MovieRentals = base.CreateObjectSet<MovieRental>("MovieRentals");
                }
                return _MovieRentals;
            }
        }
        private ObjectSet<MovieRental> _MovieRentals;
    
        #endregion
        #region AddTo Methods
            
        /// <summary>
        /// Deprecated Method for adding a new object to the MovieRentals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovieRentals(MovieRental movieRental)
        {
            base.AddObject("MovieRentals", movieRental);
        }
        #endregion
    }
    
    #endregion
    
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="MovieRental")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MovieRental : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new MovieRental object.
        /// </summary>
        /// <param name="rentalId">Initial value of the RentalId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="rentalDate">Initial value of the RentalDate property.</param>
        /// <param name="returnedDate">Initial value of the ReturnedDate property.</param>
        /// <param name="lateFees">Initial value of the LateFees property.</param>
        public static MovieRental CreateMovieRental(global::System.Int32 rentalId, global::System.String title, global::System.DateTime rentalDate, global::System.DateTime returnedDate, global::System.Decimal lateFees)
        {
            MovieRental movieRental = new MovieRental();
            movieRental.RentalId = rentalId;
            
            movieRental.Title = title;
            
            movieRental.RentalDate = rentalDate;
            
            movieRental.ReturnedDate = returnedDate;
            
            movieRental.LateFees = lateFees;
            
            return movieRental;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RentalId
        {
            get
            {
                return _RentalId;
            }
            set
            {
                if (_RentalId != value)
                {
                    OnRentalIdChanging(value);
                    ReportPropertyChanging("RentalId");
                    _RentalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RentalId");
                    OnRentalIdChanged();
                }
            }
                
        }
        private global::System.Int32 _RentalId;
        partial void OnRentalIdChanging(global::System.Int32 value);
        partial void OnRentalIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
                
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RentalDate
        {
            get
            {
                return _RentalDate;
            }
            set
            {
                OnRentalDateChanging(value);
                ReportPropertyChanging("RentalDate");
                _RentalDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RentalDate");
                OnRentalDateChanged();
            }
                
        }
        private global::System.DateTime _RentalDate;
        partial void OnRentalDateChanging(global::System.DateTime value);
        partial void OnRentalDateChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReturnedDate
        {
            get
            {
                return _ReturnedDate;
            }
            set
            {
                OnReturnedDateChanging(value);
                ReportPropertyChanging("ReturnedDate");
                _ReturnedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnedDate");
                OnReturnedDateChanged();
            }
                
        }
        private global::System.DateTime _ReturnedDate;
        partial void OnReturnedDateChanging(global::System.DateTime value);
        partial void OnReturnedDateChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LateFees
        {
            get
            {
                return _LateFees;
            }
            set
            {
                OnLateFeesChanging(value);
                ReportPropertyChanging("LateFees");
                _LateFees = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LateFees");
                OnLateFeesChanged();
            }
                
        }
        private global::System.Decimal _LateFees;
        partial void OnLateFeesChanging(global::System.Decimal value);
        partial void OnLateFeesChanged();
        
        #endregion
    
    }
    
    #endregion
    
}
