//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Bid_Job", "Job", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe7.Job), "Bid", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe7.Bid), true)]

#endregion

namespace Recipe7
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bid> Bids
        {
            get
            {
                if ((_Bids == null))
                {
                    _Bids = base.CreateObjectSet<Bid>("Bids");
                }
                return _Bids;
            }
        }
        private ObjectSet<Bid> _Bids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Job> Jobs
        {
            get
            {
                if ((_Jobs == null))
                {
                    _Jobs = base.CreateObjectSet<Job>("Jobs");
                }
                return _Jobs;
            }
        }
        private ObjectSet<Job> _Jobs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBids(Bid bid)
        {
            base.AddObject("Bids", bid);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Jobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJobs(Job job)
        {
            base.AddObject("Jobs", job);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Bid")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bid : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bid object.
        /// </summary>
        /// <param name="bidId">Initial value of the BidId property.</param>
        /// <param name="jobId">Initial value of the JobId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="bidder">Initial value of the Bidder property.</param>
        public static Bid CreateBid(global::System.Int32 bidId, global::System.Int32 jobId, global::System.Decimal amount, global::System.String bidder)
        {
            Bid bid = new Bid();
            bid.BidId = bidId;
            bid.JobId = jobId;
            bid.Amount = amount;
            bid.Bidder = bidder;
            return bid;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BidId
        {
            get
            {
                return _BidId;
            }
            set
            {
                if (_BidId != value)
                {
                    OnBidIdChanging(value);
                    ReportPropertyChanging("BidId");
                    _BidId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BidId");
                    OnBidIdChanged();
                }
            }
        }
        private global::System.Int32 _BidId;
        partial void OnBidIdChanging(global::System.Int32 value);
        partial void OnBidIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobId
        {
            get
            {
                return _JobId;
            }
            set
            {
                OnJobIdChanging(value);
                ReportPropertyChanging("JobId");
                _JobId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobId");
                OnJobIdChanged();
            }
        }
        private global::System.Int32 _JobId;
        partial void OnJobIdChanging(global::System.Int32 value);
        partial void OnJobIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bidder
        {
            get
            {
                return _Bidder;
            }
            set
            {
                OnBidderChanging(value);
                ReportPropertyChanging("Bidder");
                _Bidder = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bidder");
                OnBidderChanged();
            }
        }
        private global::System.String _Bidder;
        partial void OnBidderChanging(global::System.String value);
        partial void OnBidderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Bid_Job", "Job")]
        public Job Job
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Job>("EFRecipesModel.FK_Bid_Job", "Job").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Job>("EFRecipesModel.FK_Bid_Job", "Job").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Job> JobReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Job>("EFRecipesModel.FK_Bid_Job", "Job");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Job>("EFRecipesModel.FK_Bid_Job", "Job", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Job")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Job : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Job object.
        /// </summary>
        /// <param name="jobId">Initial value of the JobId property.</param>
        /// <param name="jobDetails">Initial value of the JobDetails property.</param>
        public static Job CreateJob(global::System.Int32 jobId, global::System.String jobDetails)
        {
            Job job = new Job();
            job.JobId = jobId;
            job.JobDetails = jobDetails;
            return job;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobId
        {
            get
            {
                return _JobId;
            }
            set
            {
                if (_JobId != value)
                {
                    OnJobIdChanging(value);
                    ReportPropertyChanging("JobId");
                    _JobId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JobId");
                    OnJobIdChanged();
                }
            }
        }
        private global::System.Int32 _JobId;
        partial void OnJobIdChanging(global::System.Int32 value);
        partial void OnJobIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JobDetails
        {
            get
            {
                return _JobDetails;
            }
            set
            {
                OnJobDetailsChanging(value);
                ReportPropertyChanging("JobDetails");
                _JobDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JobDetails");
                OnJobDetailsChanged();
            }
        }
        private global::System.String _JobDetails;
        partial void OnJobDetailsChanging(global::System.String value);
        partial void OnJobDetailsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Bid_Job", "Bid")]
        public EntityCollection<Bid> Bids
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bid>("EFRecipesModel.FK_Bid_Job", "Bid");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bid>("EFRecipesModel.FK_Bid_Job", "Bid", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
