//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]


namespace Recipe6
{
    #region Contexts
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            OnContextCreated();
        }
        #endregion
        
        #region Partial Methods
        partial void OnContextCreated();
        #endregion
        
        #region ObjectSet Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Drug> Drugs
        {
            get
            {
                if ((_Drugs == null))
                {
                    _Drugs = base.CreateObjectSet<Drug>("Drugs");
                }
                return _Drugs;
            }
        }
        private ObjectSet<Drug> _Drugs;
    
        #endregion
        #region AddTo Methods
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Drugs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrugs(Drug drug)
        {
            base.AddObject("Drugs", drug);
        }
        #endregion
    }
    
    #endregion
    
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Drug")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Experimental))]
    [KnownTypeAttribute(typeof(Medicine))]
    public abstract partial class Drug : EntityObject
    {
        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DrugId
        {
            get
            {
                return _DrugId;
            }
            set
            {
                if (_DrugId != value)
                {
                    OnDrugIdChanging(value);
                    ReportPropertyChanging("DrugId");
                    _DrugId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DrugId");
                    OnDrugIdChanged();
                }
            }
                
        }
        private global::System.Int32 _DrugId;
        partial void OnDrugIdChanging(global::System.Int32 value);
        partial void OnDrugIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
                
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
        
        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Experimental")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Experimental : Drug
    {
        #region Factory Method
        /// <summary>
        /// Create a new Experimental object.
        /// </summary>
        /// <param name="drugId">Initial value of the DrugId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Experimental CreateExperimental(global::System.Int32 drugId, global::System.String name)
        {
            Experimental experimental = new Experimental();
            experimental.DrugId = drugId;
            
            experimental.Name = name;
            
            return experimental;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrincipalResearcher
        {
            get
            {
                return _PrincipalResearcher;
            }
            set
            {
                OnPrincipalResearcherChanging(value);
                ReportPropertyChanging("PrincipalResearcher");
                _PrincipalResearcher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrincipalResearcher");
                OnPrincipalResearcherChanged();
            }
                
        }
        private global::System.String _PrincipalResearcher;
        partial void OnPrincipalResearcherChanging(global::System.String value);
        partial void OnPrincipalResearcherChanged();
        
        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Medicine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medicine : Drug
    {
        #region Factory Method
        /// <summary>
        /// Create a new Medicine object.
        /// </summary>
        /// <param name="drugId">Initial value of the DrugId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="acceptedDate">Initial value of the AcceptedDate property.</param>
        public static Medicine CreateMedicine(global::System.Int32 drugId, global::System.String name, global::System.DateTime acceptedDate)
        {
            Medicine medicine = new Medicine();
            medicine.DrugId = drugId;
            
            medicine.Name = name;
            
            medicine.AcceptedDate = acceptedDate;
            
            return medicine;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TargetPrice
        {
            get
            {
                return _TargetPrice;
            }
            set
            {
                OnTargetPriceChanging(value);
                ReportPropertyChanging("TargetPrice");
                _TargetPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetPrice");
                OnTargetPriceChanged();
            }
                
        }
        private Nullable<global::System.Decimal> _TargetPrice;
        partial void OnTargetPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnTargetPriceChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AcceptedDate
        {
            get
            {
                return _AcceptedDate;
            }
            set
            {
                OnAcceptedDateChanging(value);
                ReportPropertyChanging("AcceptedDate");
                _AcceptedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AcceptedDate");
                OnAcceptedDateChanged();
            }
                
        }
        private global::System.DateTime _AcceptedDate;
        partial void OnAcceptedDateChanging(global::System.DateTime value);
        partial void OnAcceptedDateChanged();
        
        #endregion
    
    }
    
    #endregion
    
}
