//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_AssociateSalary_Associate", "Associate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe16.Associate), "AssociateSalary", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe16.AssociateSalary), true)]

#endregion

namespace Recipe16
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Associate> Associates
        {
            get
            {
                if ((_Associates == null))
                {
                    _Associates = base.CreateObjectSet<Associate>("Associates");
                }
                return _Associates;
            }
        }
        private ObjectSet<Associate> _Associates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AssociateSalary> AssociateSalaries
        {
            get
            {
                if ((_AssociateSalaries == null))
                {
                    _AssociateSalaries = base.CreateObjectSet<AssociateSalary>("AssociateSalaries");
                }
                return _AssociateSalaries;
            }
        }
        private ObjectSet<AssociateSalary> _AssociateSalaries;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Associates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssociates(Associate associate)
        {
            base.AddObject("Associates", associate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AssociateSalaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssociateSalaries(AssociateSalary associateSalary)
        {
            base.AddObject("AssociateSalaries", associateSalary);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Associate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Associate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Associate object.
        /// </summary>
        /// <param name="associateId">Initial value of the AssociateId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Associate CreateAssociate(global::System.Int32 associateId, global::System.String name)
        {
            Associate associate = new Associate();
            associate.AssociateId = associateId;
            associate.Name = name;
            return associate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AssociateId
        {
            get
            {
                return _AssociateId;
            }
            set
            {
                if (_AssociateId != value)
                {
                    OnAssociateIdChanging(value);
                    ReportPropertyChanging("AssociateId");
                    _AssociateId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AssociateId");
                    OnAssociateIdChanged();
                }
            }
        }
        private global::System.Int32 _AssociateId;
        partial void OnAssociateIdChanging(global::System.Int32 value);
        partial void OnAssociateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_AssociateSalary_Associate", "AssociateSalary")]
        public EntityCollection<AssociateSalary> AssociateSalaries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AssociateSalary>("EFRecipesModel.FK_AssociateSalary_Associate", "AssociateSalary");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AssociateSalary>("EFRecipesModel.FK_AssociateSalary_Associate", "AssociateSalary", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="AssociateSalary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AssociateSalary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AssociateSalary object.
        /// </summary>
        /// <param name="salaryId">Initial value of the SalaryId property.</param>
        /// <param name="associateId">Initial value of the AssociateId property.</param>
        /// <param name="salary">Initial value of the Salary property.</param>
        /// <param name="salaryDate">Initial value of the SalaryDate property.</param>
        public static AssociateSalary CreateAssociateSalary(global::System.Int32 salaryId, global::System.Int32 associateId, global::System.Decimal salary, global::System.DateTime salaryDate)
        {
            AssociateSalary associateSalary = new AssociateSalary();
            associateSalary.SalaryId = salaryId;
            associateSalary.AssociateId = associateId;
            associateSalary.Salary = salary;
            associateSalary.SalaryDate = salaryDate;
            return associateSalary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SalaryId
        {
            get
            {
                return _SalaryId;
            }
            set
            {
                if (_SalaryId != value)
                {
                    OnSalaryIdChanging(value);
                    ReportPropertyChanging("SalaryId");
                    _SalaryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SalaryId");
                    OnSalaryIdChanged();
                }
            }
        }
        private global::System.Int32 _SalaryId;
        partial void OnSalaryIdChanging(global::System.Int32 value);
        partial void OnSalaryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AssociateId
        {
            get
            {
                return _AssociateId;
            }
            set
            {
                OnAssociateIdChanging(value);
                ReportPropertyChanging("AssociateId");
                _AssociateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssociateId");
                OnAssociateIdChanged();
            }
        }
        private global::System.Int32 _AssociateId;
        partial void OnAssociateIdChanging(global::System.Int32 value);
        partial void OnAssociateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private global::System.Decimal _Salary;
        partial void OnSalaryChanging(global::System.Decimal value);
        partial void OnSalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SalaryDate
        {
            get
            {
                return _SalaryDate;
            }
            set
            {
                OnSalaryDateChanging(value);
                ReportPropertyChanging("SalaryDate");
                _SalaryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalaryDate");
                OnSalaryDateChanged();
            }
        }
        private global::System.DateTime _SalaryDate;
        partial void OnSalaryDateChanging(global::System.DateTime value);
        partial void OnSalaryDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_AssociateSalary_Associate", "Associate")]
        public Associate Associate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_AssociateSalary_Associate", "Associate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_AssociateSalary_Associate", "Associate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Associate> AssociateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_AssociateSalary_Associate", "Associate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Associate>("EFRecipesModel.FK_AssociateSalary_Associate", "Associate", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
