//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Recipe11
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ParkingTicket> ParkingTickets
        {
            get
            {
                if ((_ParkingTickets == null))
                {
                    _ParkingTickets = base.CreateObjectSet<ParkingTicket>("ParkingTickets");
                }
                return _ParkingTickets;
            }
        }
        private ObjectSet<ParkingTicket> _ParkingTickets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ParkingTickets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParkingTickets(ParkingTicket parkingTicket)
        {
            base.AddObject("ParkingTickets", parkingTicket);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="ParkingTicket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParkingTicket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ParkingTicket object.
        /// </summary>
        /// <param name="ticketId">Initial value of the TicketId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="paid">Initial value of the Paid property.</param>
        /// <param name="timeStamp">Initial value of the TimeStamp property.</param>
        public static ParkingTicket CreateParkingTicket(global::System.Int32 ticketId, global::System.Decimal amount, global::System.DateTime createDate, global::System.Boolean paid, global::System.Byte[] timeStamp)
        {
            ParkingTicket parkingTicket = new ParkingTicket();
            parkingTicket.TicketId = ticketId;
            parkingTicket.Amount = amount;
            parkingTicket.CreateDate = createDate;
            parkingTicket.Paid = paid;
            parkingTicket.TimeStamp = timeStamp;
            return parkingTicket;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TicketId
        {
            get
            {
                return _TicketId;
            }
            set
            {
                if (_TicketId != value)
                {
                    OnTicketIdChanging(value);
                    ReportPropertyChanging("TicketId");
                    _TicketId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TicketId");
                    OnTicketIdChanged();
                }
            }
        }
        private global::System.Int32 _TicketId;
        partial void OnTicketIdChanging(global::System.Int32 value);
        partial void OnTicketIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Paid
        {
            get
            {
                return _Paid;
            }
            set
            {
                OnPaidChanging(value);
                ReportPropertyChanging("Paid");
                _Paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paid");
                OnPaidChanged();
            }
        }
        private global::System.Boolean _Paid;
        partial void OnPaidChanging(global::System.Boolean value);
        partial void OnPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PaidDate
        {
            get
            {
                return _PaidDate;
            }
            set
            {
                OnPaidDateChanging(value);
                ReportPropertyChanging("PaidDate");
                _PaidDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaidDate");
                OnPaidDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PaidDate;
        partial void OnPaidDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPaidDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] TimeStamp
        {
            get
            {
                return StructuralObject.GetValidValue(_TimeStamp);
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.Byte[] _TimeStamp;
        partial void OnTimeStampChanging(global::System.Byte[] value);
        partial void OnTimeStampChanged();

        #endregion
    
    }

    #endregion
    
}
