//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Accident_Worker", "Worker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe11.Worker), "Accident", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe11.Accident), true)]

#endregion

namespace Recipe11
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Accident> Accidents
        {
            get
            {
                if ((_Accidents == null))
                {
                    _Accidents = base.CreateObjectSet<Accident>("Accidents");
                }
                return _Accidents;
            }
        }
        private ObjectSet<Accident> _Accidents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Worker> Workers
        {
            get
            {
                if ((_Workers == null))
                {
                    _Workers = base.CreateObjectSet<Worker>("Workers");
                }
                return _Workers;
            }
        }
        private ObjectSet<Worker> _Workers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accidents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccidents(Accident accident)
        {
            base.AddObject("Accidents", accident);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkers(Worker worker)
        {
            base.AddObject("Workers", worker);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Accident")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Accident : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Accident object.
        /// </summary>
        /// <param name="accidentId">Initial value of the AccidentId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="severity">Initial value of the Severity property.</param>
        /// <param name="workerId">Initial value of the WorkerId property.</param>
        public static Accident CreateAccident(global::System.Int32 accidentId, global::System.String description, global::System.Int32 severity, global::System.Int32 workerId)
        {
            Accident accident = new Accident();
            accident.AccidentId = accidentId;
            accident.Description = description;
            accident.Severity = severity;
            accident.WorkerId = workerId;
            return accident;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccidentId
        {
            get
            {
                return _AccidentId;
            }
            set
            {
                if (_AccidentId != value)
                {
                    OnAccidentIdChanging(value);
                    ReportPropertyChanging("AccidentId");
                    _AccidentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccidentId");
                    OnAccidentIdChanged();
                }
            }
        }
        private global::System.Int32 _AccidentId;
        partial void OnAccidentIdChanging(global::System.Int32 value);
        partial void OnAccidentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Severity
        {
            get
            {
                return _Severity;
            }
            set
            {
                OnSeverityChanging(value);
                ReportPropertyChanging("Severity");
                _Severity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Severity");
                OnSeverityChanged();
            }
        }
        private global::System.Int32 _Severity;
        partial void OnSeverityChanging(global::System.Int32 value);
        partial void OnSeverityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkerId
        {
            get
            {
                return _WorkerId;
            }
            set
            {
                OnWorkerIdChanging(value);
                ReportPropertyChanging("WorkerId");
                _WorkerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorkerId");
                OnWorkerIdChanged();
            }
        }
        private global::System.Int32 _WorkerId;
        partial void OnWorkerIdChanging(global::System.Int32 value);
        partial void OnWorkerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Accident_Worker", "Worker")]
        public Worker Worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("EFRecipesModel.FK_Accident_Worker", "Worker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("EFRecipesModel.FK_Accident_Worker", "Worker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Worker> WorkerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("EFRecipesModel.FK_Accident_Worker", "Worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Worker>("EFRecipesModel.FK_Accident_Worker", "Worker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Worker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Worker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Worker object.
        /// </summary>
        /// <param name="workerId">Initial value of the WorkerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Worker CreateWorker(global::System.Int32 workerId, global::System.String name)
        {
            Worker worker = new Worker();
            worker.WorkerId = workerId;
            worker.Name = name;
            return worker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkerId
        {
            get
            {
                return _WorkerId;
            }
            set
            {
                if (_WorkerId != value)
                {
                    OnWorkerIdChanging(value);
                    ReportPropertyChanging("WorkerId");
                    _WorkerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkerId");
                    OnWorkerIdChanged();
                }
            }
        }
        private global::System.Int32 _WorkerId;
        partial void OnWorkerIdChanging(global::System.Int32 value);
        partial void OnWorkerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Accident_Worker", "Accident")]
        public EntityCollection<Accident> Accidents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Accident>("EFRecipesModel.FK_Accident_Worker", "Accident");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Accident>("EFRecipesModel.FK_Accident_Worker", "Accident", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
