//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

#region EDM Relationship Metadata
[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Reservation_Hotel", "Hotel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe5.Hotel), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe5.Reservation), true)]
[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Reservation_Visitor", "Visitor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe5.Visitor), "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe5.Reservation), true)]
#endregion

namespace Recipe5
{
    #region Contexts
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            OnContextCreated();
        }
        #endregion
        
        #region Partial Methods
        partial void OnContextCreated();
        #endregion
        
        #region ObjectSet Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hotel> Hotels
        {
            get
            {
                if ((_Hotels == null))
                {
                    _Hotels = base.CreateObjectSet<Hotel>("Hotels");
                }
                return _Hotels;
            }
        }
        private ObjectSet<Hotel> _Hotels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservation> Reservations
        {
            get
            {
                if ((_Reservations == null))
                {
                    _Reservations = base.CreateObjectSet<Reservation>("Reservations");
                }
                return _Reservations;
            }
        }
        private ObjectSet<Reservation> _Reservations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Visitor> Visitors
        {
            get
            {
                if ((_Visitors == null))
                {
                    _Visitors = base.CreateObjectSet<Visitor>("Visitors");
                }
                return _Visitors;
            }
        }
        private ObjectSet<Visitor> _Visitors;
    
        #endregion
        #region AddTo Methods
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Hotels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotels(Hotel hotel)
        {
            base.AddObject("Hotels", hotel);
        }
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservations(Reservation reservation)
        {
            base.AddObject("Reservations", reservation);
        }
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Visitors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitors(Visitor visitor)
        {
            base.AddObject("Visitors", visitor);
        }
        #endregion
    }
    
    #endregion
    
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Hotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hotel : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new Hotel object.
        /// </summary>
        /// <param name="hotelId">Initial value of the HotelId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Hotel CreateHotel(global::System.Int32 hotelId, global::System.String name)
        {
            Hotel hotel = new Hotel();
            hotel.HotelId = hotelId;
            
            hotel.Name = name;
            
            return hotel;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HotelId
        {
            get
            {
                return _HotelId;
            }
            set
            {
                if (_HotelId != value)
                {
                    OnHotelIdChanging(value);
                    ReportPropertyChanging("HotelId");
                    _HotelId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HotelId");
                    OnHotelIdChanged();
                }
            }
                
        }
        private global::System.Int32 _HotelId;
        partial void OnHotelIdChanging(global::System.Int32 value);
        partial void OnHotelIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
                
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Reservation_Hotel", "Reservation")] 
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("EFRecipesModel.FK_Reservation_Hotel", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("EFRecipesModel.FK_Reservation_Hotel", "Reservation", value);
                }
            }
        }
        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new Reservation object.
        /// </summary>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="roomNumber">Initial value of the RoomNumber property.</param>
        /// <param name="cost">Initial value of the Cost property.</param>
        /// <param name="reservationDate">Initial value of the ReservationDate property.</param>
        /// <param name="visitorId">Initial value of the VisitorId property.</param>
        /// <param name="hotelId">Initial value of the HotelId property.</param>
        public static Reservation CreateReservation(global::System.Int32 reservationId, global::System.Int32 roomNumber, global::System.Decimal cost, global::System.DateTime reservationDate, global::System.Int32 visitorId, global::System.Int32 hotelId)
        {
            Reservation reservation = new Reservation();
            reservation.ReservationId = reservationId;
            
            reservation.RoomNumber = roomNumber;
            
            reservation.Cost = cost;
            
            reservation.ReservationDate = reservationDate;
            
            reservation.VisitorId = visitorId;
            
            reservation.HotelId = hotelId;
            
            return reservation;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                if (_ReservationId != value)
                {
                    OnReservationIdChanging(value);
                    ReportPropertyChanging("ReservationId");
                    _ReservationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReservationId");
                    OnReservationIdChanged();
                }
            }
                
        }
        private global::System.Int32 _ReservationId;
        partial void OnReservationIdChanging(global::System.Int32 value);
        partial void OnReservationIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoomNumber
        {
            get
            {
                return _RoomNumber;
            }
            set
            {
                OnRoomNumberChanging(value);
                ReportPropertyChanging("RoomNumber");
                _RoomNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomNumber");
                OnRoomNumberChanged();
            }
                
        }
        private global::System.Int32 _RoomNumber;
        partial void OnRoomNumberChanging(global::System.Int32 value);
        partial void OnRoomNumberChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                OnCostChanging(value);
                ReportPropertyChanging("Cost");
                _Cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cost");
                OnCostChanged();
            }
                
        }
        private global::System.Decimal _Cost;
        partial void OnCostChanging(global::System.Decimal value);
        partial void OnCostChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReservationDate
        {
            get
            {
                return _ReservationDate;
            }
            set
            {
                OnReservationDateChanging(value);
                ReportPropertyChanging("ReservationDate");
                _ReservationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReservationDate");
                OnReservationDateChanged();
            }
                
        }
        private global::System.DateTime _ReservationDate;
        partial void OnReservationDateChanging(global::System.DateTime value);
        partial void OnReservationDateChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VisitorId
        {
            get
            {
                return _VisitorId;
            }
            set
            {
                OnVisitorIdChanging(value);
                ReportPropertyChanging("VisitorId");
                _VisitorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitorId");
                OnVisitorIdChanged();
            }
                
        }
        private global::System.Int32 _VisitorId;
        partial void OnVisitorIdChanging(global::System.Int32 value);
        partial void OnVisitorIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HotelId
        {
            get
            {
                return _HotelId;
            }
            set
            {
                OnHotelIdChanging(value);
                ReportPropertyChanging("HotelId");
                _HotelId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HotelId");
                OnHotelIdChanged();
            }
                
        }
        private global::System.Int32 _HotelId;
        partial void OnHotelIdChanging(global::System.Int32 value);
        partial void OnHotelIdChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Reservation_Hotel", "Hotel")] 
        public Hotel Hotel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("EFRecipesModel.FK_Reservation_Hotel", "Hotel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("EFRecipesModel.FK_Reservation_Hotel", "Hotel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hotel> HotelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("EFRecipesModel.FK_Reservation_Hotel", "Hotel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hotel>("EFRecipesModel.FK_Reservation_Hotel", "Hotel", value);
                }
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Reservation_Visitor", "Visitor")] 
        public Visitor Visitor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visitor>("EFRecipesModel.FK_Reservation_Visitor", "Visitor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visitor>("EFRecipesModel.FK_Reservation_Visitor", "Visitor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Visitor> VisitorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Visitor>("EFRecipesModel.FK_Reservation_Visitor", "Visitor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Visitor>("EFRecipesModel.FK_Reservation_Visitor", "Visitor", value);
                }
            }
        }
        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Visitor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visitor : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new Visitor object.
        /// </summary>
        /// <param name="vistorId">Initial value of the VistorId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Visitor CreateVisitor(global::System.Int32 vistorId, global::System.String name)
        {
            Visitor visitor = new Visitor();
            visitor.VistorId = vistorId;
            
            visitor.Name = name;
            
            return visitor;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VistorId
        {
            get
            {
                return _VistorId;
            }
            set
            {
                if (_VistorId != value)
                {
                    OnVistorIdChanging(value);
                    ReportPropertyChanging("VistorId");
                    _VistorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VistorId");
                    OnVistorIdChanged();
                }
            }
                
        }
        private global::System.Int32 _VistorId;
        partial void OnVistorIdChanging(global::System.Int32 value);
        partial void OnVistorIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
                
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Reservation_Visitor", "Reservation")] 
        public EntityCollection<Reservation> Reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation>("EFRecipesModel.FK_Reservation_Visitor", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation>("EFRecipesModel.FK_Reservation_Visitor", "Reservation", value);
                }
            }
        }
        #endregion
    }
    
    #endregion
    
}
