//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Pay_Associate", "Associate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe7.Associate), "Paycheck", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe7.Paycheck), true)]

#endregion

namespace Recipe7
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Associate> Associates
        {
            get
            {
                if ((_Associates == null))
                {
                    _Associates = base.CreateObjectSet<Associate>("Associates");
                }
                return _Associates;
            }
        }
        private ObjectSet<Associate> _Associates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Paycheck> Paychecks
        {
            get
            {
                if ((_Paychecks == null))
                {
                    _Paychecks = base.CreateObjectSet<Paycheck>("Paychecks");
                }
                return _Paychecks;
            }
        }
        private ObjectSet<Paycheck> _Paychecks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Associates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssociates(Associate associate)
        {
            base.AddObject("Associates", associate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Paychecks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaychecks(Paycheck paycheck)
        {
            base.AddObject("Paychecks", paycheck);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Associate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Associate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Associate object.
        /// </summary>
        /// <param name="associateId">Initial value of the AssociateId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="city">Initial value of the City property.</param>
        public static Associate CreateAssociate(global::System.Int32 associateId, global::System.String name, global::System.String city)
        {
            Associate associate = new Associate();
            associate.AssociateId = associateId;
            associate.Name = name;
            associate.City = city;
            return associate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AssociateId
        {
            get
            {
                return _AssociateId;
            }
            set
            {
                if (_AssociateId != value)
                {
                    OnAssociateIdChanging(value);
                    ReportPropertyChanging("AssociateId");
                    _AssociateId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AssociateId");
                    OnAssociateIdChanged();
                }
            }
        }
        private global::System.Int32 _AssociateId;
        partial void OnAssociateIdChanging(global::System.Int32 value);
        partial void OnAssociateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Pay_Associate", "Paycheck")]
        public EntityCollection<Paycheck> Paychecks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Paycheck>("EFRecipesModel.FK_Pay_Associate", "Paycheck");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Paycheck>("EFRecipesModel.FK_Pay_Associate", "Paycheck", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Paycheck")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Paycheck : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Paycheck object.
        /// </summary>
        /// <param name="payCheckId">Initial value of the PayCheckId property.</param>
        /// <param name="associateId">Initial value of the AssociateId property.</param>
        /// <param name="payDate">Initial value of the PayDate property.</param>
        /// <param name="gross">Initial value of the Gross property.</param>
        public static Paycheck CreatePaycheck(global::System.Int32 payCheckId, global::System.Int32 associateId, global::System.DateTime payDate, global::System.Decimal gross)
        {
            Paycheck paycheck = new Paycheck();
            paycheck.PayCheckId = payCheckId;
            paycheck.AssociateId = associateId;
            paycheck.PayDate = payDate;
            paycheck.Gross = gross;
            return paycheck;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PayCheckId
        {
            get
            {
                return _PayCheckId;
            }
            set
            {
                if (_PayCheckId != value)
                {
                    OnPayCheckIdChanging(value);
                    ReportPropertyChanging("PayCheckId");
                    _PayCheckId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PayCheckId");
                    OnPayCheckIdChanged();
                }
            }
        }
        private global::System.Int32 _PayCheckId;
        partial void OnPayCheckIdChanging(global::System.Int32 value);
        partial void OnPayCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AssociateId
        {
            get
            {
                return _AssociateId;
            }
            set
            {
                OnAssociateIdChanging(value);
                ReportPropertyChanging("AssociateId");
                _AssociateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssociateId");
                OnAssociateIdChanged();
            }
        }
        private global::System.Int32 _AssociateId;
        partial void OnAssociateIdChanging(global::System.Int32 value);
        partial void OnAssociateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PayDate
        {
            get
            {
                return _PayDate;
            }
            set
            {
                OnPayDateChanging(value);
                ReportPropertyChanging("PayDate");
                _PayDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayDate");
                OnPayDateChanged();
            }
        }
        private global::System.DateTime _PayDate;
        partial void OnPayDateChanging(global::System.DateTime value);
        partial void OnPayDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Gross
        {
            get
            {
                return _Gross;
            }
            set
            {
                OnGrossChanging(value);
                ReportPropertyChanging("Gross");
                _Gross = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gross");
                OnGrossChanged();
            }
        }
        private global::System.Decimal _Gross;
        partial void OnGrossChanging(global::System.Decimal value);
        partial void OnGrossChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Pay_Associate", "Associate")]
        public Associate Associate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_Pay_Associate", "Associate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_Pay_Associate", "Associate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Associate> AssociateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Associate>("EFRecipesModel.FK_Pay_Associate", "Associate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Associate>("EFRecipesModel.FK_Pay_Associate", "Associate", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
