//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

#region EDM Relationship Metadata
[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_Customer_CustomerType", "CustomerType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe1.CustomerType), "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe1.Customer), true)]
[assembly: EdmRelationshipAttribute("EFRecipesModel", "FK_CustomerEmail_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Recipe1.Customer), "CustomerEmail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Recipe1.CustomerEmail), true)]
#endregion

namespace Recipe1
{
    #region Contexts
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EFRecipesEntities : ObjectContext
    {
        #region Constructors
        /// <summary>
        /// Initializes a new EFRecipesEntities object using the connection string found in the 'EFRecipesEntities' section of the application configuration file.
        /// </summary>
        public EFRecipesEntities() : base("name=EFRecipesEntities", "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(string connectionString) : base(connectionString, "EFRecipesEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EFRecipesEntities object.
        /// </summary>
        public EFRecipesEntities(EntityConnection connection) : base(connection, "EFRecipesEntities")
        {
            OnContextCreated();
        }
        #endregion
        
        #region Partial Methods
        partial void OnContextCreated();
        #endregion
        
        #region ObjectSet Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerEmail> CustomerEmails
        {
            get
            {
                if ((_CustomerEmails == null))
                {
                    _CustomerEmails = base.CreateObjectSet<CustomerEmail>("CustomerEmails");
                }
                return _CustomerEmails;
            }
        }
        private ObjectSet<CustomerEmail> _CustomerEmails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerType> CustomerTypes
        {
            get
            {
                if ((_CustomerTypes == null))
                {
                    _CustomerTypes = base.CreateObjectSet<CustomerType>("CustomerTypes");
                }
                return _CustomerTypes;
            }
        }
        private ObjectSet<CustomerType> _CustomerTypes;
    
        #endregion
        #region AddTo Methods
            
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
            
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerEmails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerEmails(CustomerEmail customerEmail)
        {
            base.AddObject("CustomerEmails", customerEmail);
        }
            
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerTypes(CustomerType customerType)
        {
            base.AddObject("CustomerTypes", customerType);
        }
        #endregion
    }
    
    #endregion
    
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="customerTypeId">Initial value of the CustomerTypeId property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerId, global::System.String name, global::System.Int32 customerTypeId)
        {
            Customer customer = new Customer();
            customer.CustomerId = customerId;
            
            customer.Name = name;
            
            customer.CustomerTypeId = customerTypeId;
            
            return customer;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
                
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
                
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerTypeId
        {
            get
            {
                return _CustomerTypeId;
            }
            set
            {
                OnCustomerTypeIdChanging(value);
                ReportPropertyChanging("CustomerTypeId");
                _CustomerTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerTypeId");
                OnCustomerTypeIdChanged();
            }
                
        }
        private global::System.Int32 _CustomerTypeId;
        partial void OnCustomerTypeIdChanging(global::System.Int32 value);
        partial void OnCustomerTypeIdChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Customer_CustomerType", "CustomerType")] 
        public CustomerType CustomerType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerType>("EFRecipesModel.FK_Customer_CustomerType", "CustomerType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerType>("EFRecipesModel.FK_Customer_CustomerType", "CustomerType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerType> CustomerTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerType>("EFRecipesModel.FK_Customer_CustomerType", "CustomerType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerType>("EFRecipesModel.FK_Customer_CustomerType", "CustomerType", value);
                }
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_CustomerEmail_Customer", "CustomerEmail")] 
        public EntityCollection<CustomerEmail> CustomerEmails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerEmail>("EFRecipesModel.FK_CustomerEmail_Customer", "CustomerEmail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerEmail>("EFRecipesModel.FK_CustomerEmail_Customer", "CustomerEmail", value);
                }
            }
        }
        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="CustomerEmail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerEmail : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new CustomerEmail object.
        /// </summary>
        /// <param name="customerEmailId">Initial value of the CustomerEmailId property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static CustomerEmail CreateCustomerEmail(global::System.Int32 customerEmailId, global::System.Int32 customerId, global::System.String email)
        {
            CustomerEmail customerEmail = new CustomerEmail();
            customerEmail.CustomerEmailId = customerEmailId;
            
            customerEmail.CustomerId = customerId;
            
            customerEmail.Email = email;
            
            return customerEmail;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerEmailId
        {
            get
            {
                return _CustomerEmailId;
            }
            set
            {
                if (_CustomerEmailId != value)
                {
                    OnCustomerEmailIdChanging(value);
                    ReportPropertyChanging("CustomerEmailId");
                    _CustomerEmailId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerEmailId");
                    OnCustomerEmailIdChanged();
                }
            }
                
        }
        private global::System.Int32 _CustomerEmailId;
        partial void OnCustomerEmailIdChanging(global::System.Int32 value);
        partial void OnCustomerEmailIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
                
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
                
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_CustomerEmail_Customer", "Customer")] 
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EFRecipesModel.FK_CustomerEmail_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EFRecipesModel.FK_CustomerEmail_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EFRecipesModel.FK_CustomerEmail_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("EFRecipesModel.FK_CustomerEmail_Customer", "Customer", value);
                }
            }
        }
        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFRecipesModel", Name="CustomerType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerType : EntityObject
    {
        #region Factory Method
        /// <summary>
        /// Create a new CustomerType object.
        /// </summary>
        /// <param name="customerTypeId">Initial value of the CustomerTypeId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static CustomerType CreateCustomerType(global::System.Int32 customerTypeId, global::System.String description)
        {
            CustomerType customerType = new CustomerType();
            customerType.CustomerTypeId = customerTypeId;
            
            customerType.Description = description;
            
            return customerType;
        }
        #endregion

        #region Primitive Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerTypeId
        {
            get
            {
                return _CustomerTypeId;
            }
            set
            {
                if (_CustomerTypeId != value)
                {
                    OnCustomerTypeIdChanging(value);
                    ReportPropertyChanging("CustomerTypeId");
                    _CustomerTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerTypeId");
                    OnCustomerTypeIdChanged();
                }
            }
                
        }
        private global::System.Int32 _CustomerTypeId;
        partial void OnCustomerTypeIdChanging(global::System.Int32 value);
        partial void OnCustomerTypeIdChanged();
        
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
                
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
        
        #endregion
    
        #region Navigation Properties
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EFRecipesModel", "FK_Customer_CustomerType", "Customer")] 
        public EntityCollection<Customer> Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer>("EFRecipesModel.FK_Customer_CustomerType", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer>("EFRecipesModel.FK_Customer_CustomerType", "Customer", value);
                }
            }
        }
        #endregion
    }
    
    #endregion
    
}
